version: '3'

services:
  database:
    image: postgres:12.2
    volumes:
    - ../django_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: fragalysis
      POSTGRES_DB: frag
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
    - "5432:5432"
  tests:
    image: ${LOADER_NAMESPACE}/fragalysis-loader:latest
    command: ["/code/wait-for-it.sh", "database:5432", "--", "/bin/bash", "/code/test_entry.sh"]
    volumes:
    - ../logs:/code/logs/
    - ../media:/code/media/
    ports:
    - "80:80"
    depends_on:
    - database
